-- Manually applies the EF Core migration "AddDriversDistanceAndBookingDetails"
-- (generated by Add-Migration, but Update-Database/dotnet-ef won't run it on
-- this machine). Run this ONCE against CarRentalDB in SSMS. It does exactly
-- what that migration's Up() method does, then registers it in
-- __EFMigrationsHistory so EF considers it applied and won't try to redo it.
-- Safe to re-run: it checks first and does nothing if already applied.

USE CarRentalDB;
GO

IF EXISTS (SELECT 1 FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20260912162841_AddDriversDistanceAndBookingDetails')
BEGIN
    PRINT 'Already applied - nothing to do.';
    RETURN;
END
GO

BEGIN TRANSACTION;
GO

ALTER TABLE [mst_car] ADD [assigned_driver_id] int NULL;
GO

CREATE TABLE [mst_driver] (
    [driver_id] int NOT NULL IDENTITY(1,1),
    [driver_name] nvarchar(100) NOT NULL,
    [phone_number] nvarchar(20) NOT NULL,
    [license_number] nvarchar(30) NOT NULL,
    [is_active] bit NOT NULL,
    [created_date] datetime2 NOT NULL,
    CONSTRAINT [PK_mst_driver] PRIMARY KEY ([driver_id])
);
GO

CREATE TABLE [mst_location_distance] (
    [distance_id] int NOT NULL IDENTITY(1,1),
    [from_location_id] int NOT NULL,
    [to_location_id] int NOT NULL,
    [distance_km] decimal(8,2) NOT NULL,
    CONSTRAINT [PK_mst_location_distance] PRIMARY KEY ([distance_id]),
    CONSTRAINT [FK_mst_location_distance_mst_location_from_location_id] FOREIGN KEY ([from_location_id]) REFERENCES [mst_location] ([location_id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_mst_location_distance_mst_location_to_location_id] FOREIGN KEY ([to_location_id]) REFERENCES [mst_location] ([location_id]) ON DELETE NO ACTION
);
GO

CREATE TABLE [trn_booking_detail] (
    [booking_detail_id] int NOT NULL IDENTITY(1,1),
    [booking_id] int NOT NULL,
    [car_id] int NOT NULL,
    [car_name] nvarchar(100) NOT NULL,
    [car_brand] nvarchar(100) NOT NULL,
    [from_location_id] int NOT NULL,
    [from_location_name] nvarchar(100) NOT NULL,
    [to_location_id] int NOT NULL,
    [to_location_name] nvarchar(100) NOT NULL,
    [distance_km] decimal(8,2) NOT NULL,
    [driver_id] int NULL,
    [driver_name] nvarchar(100) NOT NULL,
    [booking_date] datetime2 NOT NULL,
    [booking_time] nvarchar(10) NOT NULL,
    [amount] decimal(10,2) NOT NULL,
    [created_date] datetime2 NOT NULL,
    CONSTRAINT [PK_trn_booking_detail] PRIMARY KEY ([booking_detail_id]),
    CONSTRAINT [FK_trn_booking_detail_mst_driver_driver_id] FOREIGN KEY ([driver_id]) REFERENCES [mst_driver] ([driver_id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_trn_booking_detail_mst_location_from_location_id] FOREIGN KEY ([from_location_id]) REFERENCES [mst_location] ([location_id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_trn_booking_detail_mst_location_to_location_id] FOREIGN KEY ([to_location_id]) REFERENCES [mst_location] ([location_id]) ON DELETE NO ACTION,
    CONSTRAINT [FK_trn_booking_detail_trn_booking_booking_id] FOREIGN KEY ([booking_id]) REFERENCES [trn_booking] ([booking_id]) ON DELETE CASCADE
);
GO

UPDATE [mst_car] SET [assigned_driver_id] = 1 WHERE [car_id] = 1;
UPDATE [mst_car] SET [assigned_driver_id] = 2 WHERE [car_id] = 2;
UPDATE [mst_car] SET [assigned_driver_id] = 3 WHERE [car_id] = 3;
UPDATE [mst_car] SET [assigned_driver_id] = 4 WHERE [car_id] = 4;
UPDATE [mst_car] SET [assigned_driver_id] = 5 WHERE [car_id] = 5;
UPDATE [mst_car] SET [assigned_driver_id] = 6 WHERE [car_id] = 6;
UPDATE [mst_car] SET [assigned_driver_id] = 7 WHERE [car_id] = 7;
UPDATE [mst_car] SET [assigned_driver_id] = 8 WHERE [car_id] = 8;
GO

SET IDENTITY_INSERT [mst_driver] ON;
INSERT INTO [mst_driver] ([driver_id], [created_date], [driver_name], [is_active], [license_number], [phone_number])
VALUES
    (1, '2026-01-01T00:00:00.000', N'Ramesh Yadav', 1, N'MP-DL-000001', N'9800000001'),
    (2, '2026-01-01T00:00:00.000', N'Suresh Kumar', 1, N'MP-DL-000002', N'9800000002'),
    (3, '2026-01-01T00:00:00.000', N'Anil Verma', 1, N'DL-DL-000003', N'9800000003'),
    (4, '2026-01-01T00:00:00.000', N'Vikram Singh', 1, N'MP-DL-000004', N'9800000004'),
    (5, '2026-01-01T00:00:00.000', N'Rajesh Chauhan', 1, N'MH-DL-000005', N'9800000005'),
    (6, '2026-01-01T00:00:00.000', N'Manoj Tiwari', 1, N'MP-DL-000006', N'9800000006'),
    (7, '2026-01-01T00:00:00.000', N'Sanjay Mehta', 1, N'DL-DL-000007', N'9800000007'),
    (8, '2026-01-01T00:00:00.000', N'Deepak Rathore', 1, N'MP-DL-000008', N'9800000008');
SET IDENTITY_INSERT [mst_driver] OFF;
GO

SET IDENTITY_INSERT [mst_location_distance] ON;
INSERT INTO [mst_location_distance] ([distance_id], [distance_km], [from_location_id], [to_location_id])
VALUES
    (1, 190.00, 1, 2),
    (2, 190.00, 2, 1),
    (3, 740.00, 1, 3),
    (4, 740.00, 3, 1),
    (5, 780.00, 1, 4),
    (6, 780.00, 4, 1),
    (7, 820.00, 2, 3),
    (8, 820.00, 3, 2),
    (9, 580.00, 2, 4),
    (10, 580.00, 4, 2),
    (11, 1400.00, 3, 4),
    (12, 1400.00, 4, 3);
SET IDENTITY_INSERT [mst_location_distance] OFF;
GO

CREATE INDEX [IX_mst_car_assigned_driver_id] ON [mst_car] ([assigned_driver_id]);
GO

CREATE UNIQUE INDEX [IX_mst_location_distance_from_location_id_to_location_id] ON [mst_location_distance] ([from_location_id], [to_location_id]);
GO

CREATE INDEX [IX_mst_location_distance_to_location_id] ON [mst_location_distance] ([to_location_id]);
GO

CREATE UNIQUE INDEX [IX_trn_booking_detail_booking_id] ON [trn_booking_detail] ([booking_id]);
GO

CREATE INDEX [IX_trn_booking_detail_driver_id] ON [trn_booking_detail] ([driver_id]);
GO

CREATE INDEX [IX_trn_booking_detail_from_location_id] ON [trn_booking_detail] ([from_location_id]);
GO

CREATE INDEX [IX_trn_booking_detail_to_location_id] ON [trn_booking_detail] ([to_location_id]);
GO

ALTER TABLE [mst_car] ADD CONSTRAINT [FK_mst_car_mst_driver_assigned_driver_id] FOREIGN KEY ([assigned_driver_id]) REFERENCES [mst_driver] ([driver_id]) ON DELETE NO ACTION;
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20260912162841_AddDriversDistanceAndBookingDetails', N'10.0.0');
GO

COMMIT TRANSACTION;
GO

PRINT 'Done: mst_driver, mst_location_distance and trn_booking_detail created and seeded; mst_car.assigned_driver_id added and populated; migration registered.';
GO
