-- Manually applies the EF Core migration "AddPhoneNumberToUser"
-- (generated by Add-Migration, but Update-Database/dotnet-ef won't run it on
-- this machine). Run this ONCE against CarRentalDB in SSMS. It does exactly
-- what that migration's Up() method does, then registers it in
-- __EFMigrationsHistory so EF considers it applied and won't try to redo it.
-- Safe to re-run: it checks first and does nothing if already applied.

USE CarRentalDB;
GO

IF EXISTS (SELECT 1 FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20260913080000_AddPhoneNumberToUser')
BEGIN
    PRINT 'Already applied - nothing to do.';
    RETURN;
END
GO

BEGIN TRANSACTION;
GO

ALTER TABLE [mst_user] ADD [phone_number] nvarchar(15) NOT NULL DEFAULT '';
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20260913080000_AddPhoneNumberToUser', N'10.0.0');
GO

COMMIT TRANSACTION;
GO

PRINT 'Done: mst_user.phone_number added; migration registered.';
GO
