// <auto-generated />
using System;
using CarRentalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912055916_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRentalAPI.Entities.MstCar", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("brand");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("car_name");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("int")
                        .HasColumnName("car_type_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("fuel_type");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("is_available");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_per_day");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("rating");

                    b.Property<int>("Seats")
                        .HasColumnType("int")
                        .HasColumnName("seats");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("transmission");

                    b.HasKey("CarId");

                    b.HasIndex("CarTypeId");

                    b.HasIndex("LocationId");

                    b.ToTable("mst_car");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Brand = "Maruti Suzuki",
                            CarName = "Swift Dzire",
                            CarTypeId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ImageUrl = "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=600&q=80",
                            IsAvailable = true,
                            LocationId = 1,
                            PricePerDay = 1800m,
                            Rating = 4.4m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = 2,
                            Brand = "Hyundai",
                            CarName = "Creta",
                            CarTypeId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ImageUrl = "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=600&q=80",
                            IsAvailable = true,
                            LocationId = 2,
                            PricePerDay = 3200m,
                            Rating = 4.7m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            CarId = 3,
                            Brand = "Tesla",
                            CarName = "Model 3",
                            CarTypeId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Electric",
                            ImageUrl = "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=600&q=80",
                            IsAvailable = false,
                            LocationId = 3,
                            PricePerDay = 6500m,
                            Rating = 4.9m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            CarId = 4,
                            Brand = "Honda",
                            CarName = "City",
                            CarTypeId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ImageUrl = "https://images.unsplash.com/photo-1622194993926-2f30edb5f9a7?auto=format&fit=crop&w=600&q=80",
                            IsAvailable = true,
                            LocationId = 1,
                            PricePerDay = 2600m,
                            Rating = 4.5m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            CarId = 5,
                            Brand = "Toyota",
                            CarName = "Fortuner",
                            CarTypeId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ImageUrl = "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80",
                            IsAvailable = true,
                            LocationId = 4,
                            PricePerDay = 5800m,
                            Rating = 4.8m,
                            Seats = 7,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            CarId = 6,
                            Brand = "Maruti Suzuki",
                            CarName = "Baleno",
                            CarTypeId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ImageUrl = "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=600&q=80",
                            IsAvailable = true,
                            LocationId = 2,
                            PricePerDay = 1500m,
                            Rating = 4.2m,
                            Seats = 5,
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = 7,
                            Brand = "BMW",
                            CarName = "BMW 5 Series",
                            CarTypeId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ImageUrl = "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=600&q=80",
                            IsAvailable = true,
                            LocationId = 3,
                            PricePerDay = 9000m,
                            Rating = 4.9m,
                            Seats = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            CarId = 8,
                            Brand = "Tata",
                            CarName = "Nexon EV",
                            CarTypeId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Electric",
                            ImageUrl = "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=600&q=80",
                            IsAvailable = true,
                            LocationId = 1,
                            PricePerDay = 2900m,
                            Rating = 4.3m,
                            Seats = 5,
                            Transmission = "Automatic"
                        });
                });

            modelBuilder.Entity("CarRentalAPI.Entities.MstCarType", b =>
                {
                    b.Property<int>("CarTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("car_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type_name");

                    b.HasKey("CarTypeId");

                    b.ToTable("mst_car_type");

                    b.HasData(
                        new
                        {
                            CarTypeId = 1,
                            TypeName = "Sedan"
                        },
                        new
                        {
                            CarTypeId = 2,
                            TypeName = "SUV"
                        },
                        new
                        {
                            CarTypeId = 3,
                            TypeName = "Hatchback"
                        },
                        new
                        {
                            CarTypeId = 4,
                            TypeName = "Luxury"
                        },
                        new
                        {
                            CarTypeId = 5,
                            TypeName = "Electric"
                        });
                });

            modelBuilder.Entity("CarRentalAPI.Entities.MstLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city_name");

                    b.HasKey("LocationId");

                    b.ToTable("mst_location");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            CityName = "Bhopal"
                        },
                        new
                        {
                            LocationId = 2,
                            CityName = "Indore"
                        },
                        new
                        {
                            LocationId = 3,
                            CityName = "Delhi"
                        },
                        new
                        {
                            LocationId = 4,
                            CityName = "Mumbai"
                        });
                });

            modelBuilder.Entity("CarRentalAPI.Entities.MstRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("mst_role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("CarRentalAPI.Entities.MstUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("mst_user");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "demo@driveon.com",
                            FullName = "Demo User",
                            IsActive = true,
                            PasswordHash = "$2b$11$aYdgWAKTu6uNfv1xmRe6Lubhkti5R4pil8Q7l6M86Li80PtL5j8hq",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("CarRentalAPI.Entities.TblRefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("token_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_refresh_token");
                });

            modelBuilder.Entity("CarRentalAPI.Entities.TrnBooking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("booking_no");

                    b.Property<int>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("from_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("to_date");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingNo")
                        .IsUnique();

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("trn_booking");
                });

            modelBuilder.Entity("CarRentalAPI.Entities.MstCar", b =>
                {
                    b.HasOne("CarRentalAPI.Entities.MstCarType", "CarType")
                        .WithMany("Cars")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRentalAPI.Entities.MstLocation", "Location")
                        .WithMany("Cars")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CarRentalAPI.Entities.MstUser", b =>
                {
                    b.HasOne("CarRentalAPI.Entities.MstRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CarRentalAPI.Entities.TblRefreshToken", b =>
                {
                    b.HasOne("CarRentalAPI.Entities.MstUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarRentalAPI.Entities.TrnBooking", b =>
                {
                    b.HasOne("CarRentalAPI.Entities.MstCar", "Car")
                        .WithMany("Bookings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRentalAPI.Entities.MstUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarRentalAPI.Entities.MstCar", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CarRentalAPI.Entities.MstCarType", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarRentalAPI.Entities.MstLocation", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarRentalAPI.Entities.MstRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CarRentalAPI.Entities.MstUser", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
